### ISSUE TITLE
Cog paths do not work on new streets

### ISSUE THREAD

**Issue by Weirdodude101** [JawhnL5/Toontown-Level-Editor#12] opened 2015-07-01 20:48 UTC
If I try to add a cog path to my street, it crashes as I click on it to move it. If I load another street such as, Loopy lane, I can edit the cog paths all I want with no problems.
Any fix for this?

**Comment by sean5470** [comment] 2015-07-01 21:43
hmm, I'll have to try it out. I did manage to edit in some to like BBHQ one time, and it didn't crash with adding them, or battle cells.  I'll have to try on a street.

**Comment by Weirdodude101** [comment] 2015-07-02 02:31
Yea, It works with modifying them on already-made areas, it's just when you add a new one and select it crashes.

**Comment by sean5470** [comment] 2015-07-02 05:06
OK, I think I figured it out. There is a set or two one has to take for it to work without crashing. 
First step, is you have to create a visgroup and set it to be the Reparent target via the SceneGraph explorer Tab on the Level Editor Panel.  http://prntscr.com/7ntbrh   Right click on the Panda Level, and at the bottom is the add visgroup.
Then, right click the new visgroup, which will show up under the Panda Level item, and choose it to be the ReParent Target. Doing this, causes all new items inserted to automatically be placed under that visgroup until you change the reparent target.
Once those two step are done, you will want to turn on the plane (& probably grid) snapping. But I think Plane snapping is the most important so the inserted points will snap to the plane of the street.
Finally, the easiest way to insert the points, is to have your mouse cursor roughly over where you want the point to go. (with streets, they tend to be right at the edge(s) of where two street pieces meet, but can go really anywhere on the street.)
After you have your cursor where you want it, hold down the Shift key, and press the 'S' key once.
This will insert a new point right where you had your cursor.
then, just move your cursor to the next place you want one, and press the shift-S combination again.
This should insert the next point, and create the suit-edge between the two.
Now, with street points, you have to have a continuous line where the cogs will be walking. If you just randomly place points, you'll find out quickly that it only creates the suit-edge between any given two points. In order to make the line continuous, after you set the second point in a set, click back on the last in that set of two, and hit the shift-S again, then move to the next point for that set of two. This will connect the last point of one set, to the first point of the next set.

Things to note:
If after you insert the second point in a set and it doesn't draw the suit-edge line, it probably means you either don't have a visgroup in the scene, or, you don't currently have one set as the reparent target. Either route, chance are extremely high that your gonna crash when you touch one of those points.
It makes it very much easier to see the edge of the street pieces, if you place the points in wire frame mode. This can be obtained by simply toggling the "w" key while the viewer window is the active window.

If you do all that above, they seem to work as intended.

Should look at installing some checks so it does them automatically, but that will have to be when either myself or someone else has the time to dig through the code.

**Comment by Weirdodude101** [comment] 2015-07-02 05:56
Thanks for the fix sean!

**Comment by sean5470** [comment] 2015-07-02 05:58
No problem. If fact,  LOL  I looked at the code and already just pushed a fix so you can't crash when inserting them now. It'll warn you in the command box if the parent isn't a visgroup.  ;)

**Comment by Weirdodude101** [comment] 2015-07-02 06:01
Thanks!

**Comment by Weirdodude101** [comment] 2015-07-02 07:11
I have one more question, How do I make a forward path? Because if I highlight Forward nothing shows up

**Comment by sean5470** [comment] 2015-07-02 10:19
cant verify till later when not on my phone, , but from my observations, those buttons do nothing more than highlight the other nodes in that loop. i believe the loop will 'travel' in the direction in which its drawn

**Comment by sean5470** [comment] 2015-07-18 20:00
think this is now resolved and can be closed.
Also @Weirdodude101 , I was correct in the path directioning. They go in the direction of the order in which they are placed.

**Closed** 2015-08-17 21:40 UTC
